spring:
  application:
    name: stremio-addon

logging:
  level:
    org.example.stremioaddon: DEBUG

omdb:
  apiKey: ${OMDB_API_KEY}
  baseUrl: "https://www.omdbapi.com/"

jackett:
  apiKey: ${JACKETT_API_KEY}
  baseUrl: "http://localhost:9117"

